# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtreETPj2gpu6lwfvk0X8VXoiddmXv2C
"""

!pip install -q rdkit-pypi plotly flask sqlalchemy psycopg2-binary pyngrok torch torchvision google-generativeai
import os
import time
import json
import warnings
import signal
from datetime import datetime
from typing import Optional, Dict, Any
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors, Lipinski, Crippen, AllChem, Draw
from rdkit.Chem.Draw import IPythonConsole
import torch
import torch.nn as nn
import plotly.graph_objects as go
from flask import Flask, request, jsonify
from pyngrok import ngrok
from sqlalchemy import create_engine, Column, Integer, String, JSON, DateTime, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import google.generativeai as genai
warnings.filterwarnings('ignore')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
class Config:
    GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY', '')
    GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-1.5-pro')
    DATABASE_URL = os.environ.get('DATABASE_URL', '')
    SQLITE_PATH = '/content/ai_drug_discovery.db'
    MAX_RUNTIME_SECONDS = int(os.environ.get('MAX_RUNTIME_SECONDS', '120'))
    INDIAN_DISEASES = [
        'Tuberculosis', 'Dengue', 'Malaria', 'Typhoid',
        'Hepatitis', 'Diabetes Type 2', 'Cardiovascular Disease',
        'Cancer', 'COVID-19', 'Chikungunya'
    ]
if Config.GOOGLE_API_KEY:
    genai.configure(api_key=Config.GOOGLE_API_KEY)
    print('✅ Gemini configured')
else:
    print('⚠️ GOOGLE_API_KEY not set — LLM calls will be skipped')
Base = declarative_base()
class Compound(Base):
    __tablename__ = 'compounds'
    id = Column(Integer, primary_key=True)
    name = Column(String(256))
    smiles = Column(String(1024), nullable=False)
    disease_target = Column(String(256))
    properties = Column(JSON)
    created_at = Column(DateTime, default=datetime.utcnow)
class AnalysisLog(Base):
    __tablename__ = 'analysis_logs'
    id = Column(Integer, primary_key=True)
    compound_id = Column(Integer)
    analysis_type = Column(String(128))
    results = Column(JSON)
    execution_time = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)
def get_engine():
    if Config.DATABASE_URL:
        engine = create_engine(Config.DATABASE_URL, echo=False)
        print('Using PostgreSQL database')
    else:
        engine = create_engine(f'sqlite:///{Config.SQLITE_PATH}', echo=False)
        print('Using SQLite fallback database')
    return engine
engine = get_engine()
Base.metadata.create_all(engine)
SessionLocal = sessionmaker(bind=engine)
class MolecularAnalyzer:
    @staticmethod
    def validate_smiles(smiles: str) -> bool:
        try:
            mol = Chem.MolFromSmiles(smiles)
            return mol is not None
        except Exception:
            return False
    @staticmethod
    def calculate_properties(smiles: str) -> Optional[Dict[str, Any]]:
        mol = Chem.MolFromSmiles(smiles)
        if not mol:
            return None
        props = {
            'molecular_formula': Chem.rdMolDescriptors.CalcMolFormula(mol),
            'molecular_weight': round(Descriptors.MolWt(mol), 2),
            'logp': round(Crippen.MolLogP(mol), 2),
            'hbd': int(Lipinski.NumHDonors(mol)),
            'hba': int(Lipinski.NumHAcceptors(mol)),
            'tpsa': round(Descriptors.TPSA(mol), 2),
            'rotatable_bonds': int(Lipinski.NumRotatableBonds(mol))
        }
        violations = 0
        if props['molecular_weight'] > 500: violations += 1
        if props['logp'] > 5: violations += 1
        if props['hbd'] > 5: violations += 1
        if props['hba'] > 10: violations += 1
        props['lipinski_violations'] = violations
        props['drug_likeness'] = 'Excellent' if violations == 0 else 'Moderate' if violations == 1 else 'Poor'
        return props
    @staticmethod
    def calculate_fingerprint(smiles: str, nbits: int = 2048):
        mol = Chem.MolFromSmiles(smiles)
        if not mol:
            return None
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=nbits)
        arr = np.zeros((nbits,), dtype=np.float32)
        from rdkit import DataStructs
        DataStructs.ConvertToNumpyArray(fp, arr)
        return arr
class MolecularPropertyPredictor(nn.Module):
    def __init__(self, input_dim=2048):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, 512), nn.ReLU(),
            nn.Linear(512, 256), nn.ReLU(),
            nn.Linear(256, 1)
        )
    def forward(self, x):
        return self.layers(x)
toxicity_model = MolecularPropertyPredictor().to(device)
solubility_model = MolecularPropertyPredictor().to(device)
bioavailability_model = MolecularPropertyPredictor().to(device)
class PropertyPredictor:
    @staticmethod
    def _tensor(fp):
        return torch.from_numpy(fp).float().unsqueeze(0).to(device)
    @staticmethod
    def predict(smiles, model, kind):
        fp = MolecularAnalyzer.calculate_fingerprint(smiles)
        if fp is None:
            return {'error': 'Invalid SMILES'}
        with torch.no_grad():
            val = torch.sigmoid(model(PropertyPredictor._tensor(fp))).cpu().numpy()[0][0]
        if kind == 'toxicity':
            return {'toxicity_score': round(val, 3)}
        elif kind == 'solubility':
            return {'solubility_score': round(val, 3)}
        else:
            return {'bioavailability_score': round(val, 3)}
def gemini_generate(prompt: str) -> str:
    if not Config.GOOGLE_API_KEY:
        return '[Gemini not configured] ' + prompt[:400]
    try:
        model = genai.GenerativeModel(Config.GEMINI_MODEL)
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f'[Gemini error: {e}]'
def analyze_compound(smiles: str, disease: Optional[str] = None) -> Dict:
    if not MolecularAnalyzer.validate_smiles(smiles):
        return {'error': 'Invalid SMILES'}
    start = time.time()
    props = MolecularAnalyzer.calculate_properties(smiles)
    tox = PropertyPredictor.predict(smiles, toxicity_model, 'toxicity')
    sol = PropertyPredictor.predict(smiles, solubility_model, 'solubility')
    bio = PropertyPredictor.predict(smiles, bioavailability_model, 'bioavailability')
    prompt = f"""
    Analyze compound for {disease or 'unspecified disease'}:
    SMILES: {smiles}
    Properties: {json.dumps(props)}
    Predictions: Toxicity={tox}, Solubility={sol}, Bioavailability={bio}
    Provide ADME summary, risks, and improvement suggestions.
    """
    ai_text = gemini_generate(prompt)
    elapsed = time.time() - start
    session = SessionLocal()
    comp = Compound(name=smiles[:30], smiles=smiles, disease_target=disease or '', properties=props)
    session.add(comp)
    session.commit()
    session.refresh(comp)
    log = AnalysisLog(compound_id=comp.id, analysis_type='full_analysis', results={'gemini_output': ai_text}, execution_time=elapsed)
    session.add(log)
    session.commit()
    session.close()
    return {
        'compound_id': comp.id,
        'smiles': smiles,
        'properties': props,
        'ml_predictions': {'toxicity': tox, 'solubility': sol, 'bioavailability': bio},
        'ai_analysis': ai_text,
        'execution_time': round(elapsed, 2)
    }
def discover_compounds_for_disease(disease: str) -> Dict:
    prompt = f"List 5 novel compound classes for treating {disease} with SMILES and mechanism."
    ai_text = gemini_generate(prompt)
    return {'disease': disease, 'suggestions': ai_text}
app = Flask(__name__)
@app.route('/api/analyze', methods=['POST'])
def api_analyze():
    data = request.get_json(force=True)
    smiles = data.get('smiles')
    disease = data.get('disease')
    try:
        result = analyze_compound(smiles, disease)
        return jsonify({'status': 'success', 'result': result})
    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)}), 500
@app.route('/api/discover', methods=['POST'])
def api_discover():
    data = request.get_json(force=True)
    disease = data.get('disease')
    result = discover_compounds_for_disease(disease)
    return jsonify({'status': 'success', 'result': result})
@app.route('/api/compounds', methods=['GET'])
def api_compounds():
    session = SessionLocal()
    comps = session.query(Compound).all()
    out = [{'id': c.id, 'smiles': c.smiles, 'disease_target': c.disease_target, 'properties': c.properties} for c in comps]
    session.close()
    return jsonify({'status': 'success', 'compounds': out})
def run_server(public=False, port=5000):
    if public:
        url = ngrok.connect(port)
        print('Public URL:', url)
    app.run(host='0.0.0.0', port=port)
print('''\n✅ Setup complete.\nRun example:\nfrom requests import post\npost('http://127.0.0.1:5000/api/analyze', json={'smiles': 'CCO', 'disease': 'Dengue'})\n''')